import type { CheatSheetCard } from './types';

export const CHEATSHEET_CARDS: CheatSheetCard[] = [
  {
    id: 'reanimation-erwachsene',
    title: 'Reanimation Erwachsene',
    icon: '❤️',
    points: [
      'Bewusstsein & Atmung prüfen (max. 10 Sek.)',
      'Notruf 112 veranlassen',
      'HDM: 100–120/min, Tiefe 5–6 cm',
      'Verhältnis 30:2',
      'AED so früh wie möglich anlegen',
    ],
    moduleId: 'algorithmen',
    itemId: 'reanimation-erwachsene',
  },
  {
    id: 'reanimation-kinder',
    title: 'Reanimation Kinder',
    icon: '🧒',
    points: [
      'Erst 5 initiale Beatmungen',
      'Dann Thoraxkompression, mind. 1/3 des Thoraxdurchmessers',
      'Verhältnis 15:2',
      'Säugling: 2-Daumen-Technik · Kind: 1-Handballen-Technik',
      'Notruf 112 veranlassen',
    ],
    moduleId: 'algorithmen',
    itemId: 'reanimation-kinder',
  },
  {
    id: 'abcde',
    title: 'ABCDE-Schema',
    icon: '🧭',
    points: [
      'A – Airway: Atemweg frei?',
      'B – Breathing: Atmung suffizient? SpO2?',
      'C – Circulation: Puls, Rekap-Zeit, Blutung stoppen',
      'D – Disability: Bewusstsein (WASB/GCS), Pupillen, BZ',
      'E – Exposure: Ganzkörperuntersuchung, vor Auskühlung schützen',
    ],
    moduleId: 'algorithmen',
    itemId: 'abcde-herangehensweise',
  },
  {
    id: 'anaphylaxie',
    title: 'Anaphylaxie',
    icon: '🩺',
    points: [
      'Allergenzufuhr stoppen, wenn möglich',
      'Stadium I: Haut · II: Kreislauf · III: Atemwege · IV: Kreislaufstillstand',
      'Lagerung symptomorientiert (Schock- oder Oberkörperhochlage)',
      'Notarzt alarmieren',
    ],
    moduleId: 'internistischenotfaelle',
    itemId: 'anaphylaxie',
  },
  {
    id: 'manv-sichtung',
    title: 'MANV-Sichtung',
    icon: '🎪',
    points: [
      'SK I (rot): akute vitale Bedrohung — sofort',
      'SK II (gelb): schwer verletzt — aufgeschoben',
      'SK III (grün): leicht verletzt',
      'SK IV (blau): ohne Überlebenschance',
      'Gehfähig? → Atmung? → Frequenz? → Kreislauf? → Bewusstsein?',
    ],
    moduleId: 'sanitaetsdienst',
    itemId: 'manv-sichtung',
  },
  {
    id: 'schlaganfall-fast',
    title: 'Schlaganfall (FAST)',
    icon: '🩺',
    points: [
      'F – Face: hängt ein Mundwinkel?',
      'A – Arms: sinkt ein Arm ab?',
      'S – Speech: verwaschene Sprache?',
      'T – Time: Symptombeginn notieren',
      '"Time is brain" — zügiger, sicherer Transport',
    ],
    moduleId: 'internistischenotfaelle',
    itemId: 'schlaganfall-fast',
  },
  {
    id: 'verbrennungen',
    title: 'Verbrennungen',
    icon: '🩹',
    points: [
      'Grad 1: Rötung, schmerzhaft',
      'Grad 2: Blasen, sehr schmerzhaft',
      'Grad 3/4: weißlich-lederartig, schmerzlos',
      'Nur kleinflächig kühlen — Hypothermie vermeiden',
      'Steril abdecken, keine Hausmittel',
    ],
    moduleId: 'traumatologie',
    itemId: 'verbrennungen',
  },
  {
    id: 'hypoglykaemie',
    title: 'Hypoglykämie',
    icon: '🩺',
    points: [
      'Symptome: Zittern, Schwitzen, Heißhunger, Verwirrtheit',
      'Ansprechbar → Traubenzucker/gesüßtes Getränk',
      'Bewusstlos → nichts oral, stabile Seitenlage',
      'Notarzt alarmieren',
    ],
    moduleId: 'internistischenotfaelle',
    itemId: 'diabetische-notfaelle',
  },
];
